from alpine:3.15.5

RUN apk update
RUN apk add --no-cache --upgrade bash
RUN apk add git
RUN apk add ffmpeg
RUN apk add python3
RUN apk add iptables

RUN mkdir /opt/stream
WORKDIR /opt/stream

COPY stream_to_ice.sh .
COPY source.sdp .
COPY calc_ip.py .

RUN chmod a+x stream_to_ice.sh

CMD bash /opt/stream/stream_to_ice.sh
