from alpine:3.15.5

RUN apk update
RUN apk add git
RUN apk add ffmpeg
RUN apk add sox

RUN git clone --branch 1.22 https://github.com/irtlab/rtptools.git
RUN git clone --branch v1.5.0 https://github.com/Haivision/srt.git

